### ISSUE TITLE
Please not only pinned tabs, allow mark tabs for "reused Tab"

### ISSUE THREAD

**Issue by Mannshoch** [basilevs/reusetab-firefox#19]
I have several Tabs which I could use with this add-on. I use "Simple Tab Group" and "Multi-Account-Containers". In daily use I get many Mails and Chat messages I have to open. Your app could help me manage all the sites I open from links and help me reduce not used tabs.

Could you enhance your app that way that I could mark a tab for "reuse tab". I don't like to link every tab as pinned tab because I have them grouped.

**Comment by basilevs** [comment]
Sorry, I don't think this a good idea. Tab grouping would not be compatible  with self-closing tabs.
Last version of extension has blacklists and whitelists have you checked those out? They could partially help.

I'm ready to reconsider if more compelling arguments are given, or this idea gets more attention.
